#############################################################################
# Makefile for building: Shadify2
# Generated by qmake (3.1) (Qt 5.11.1)
# Project:  Shadify2.pro
# Template: app
# Command: /home/nathan/Qt/5.11.1/gcc_64/bin/qmake -o Makefile Shadify2.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -IGLFW -IGL -Iglm -I../../Qt/5.11.1/gcc_64/mkspecs/linux-g++
QMAKE         = /home/nathan/Qt/5.11.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/nathan/Qt/5.11.1/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/nathan/Qt/5.11.1/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Shadify21.0.0
DISTDIR = /home/nathan/Documents/Shadify2_save/.tmp/Shadify21.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lGL -lGLU -lGLEW -lglfw3 -lX11 -lXi -lXrandr -lXxf86vm -lXinerama -lXcursor -lrt -lm -pthread -ldl -lassimp 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		shader.cpp \
		mesh.cpp \
		object.cpp \
		glfwwindow.cpp \
		scene.cpp \
		abstract_event_handler.cpp \
		model.cpp \
		light.cpp \
		renderengine.cpp \
		camerafps.cpp \
		cameraorbit.cpp \
		camera.cpp 
OBJECTS       = main.o \
		shader.o \
		mesh.o \
		object.o \
		glfwwindow.o \
		scene.o \
		abstract_event_handler.o \
		model.o \
		light.o \
		renderengine.o \
		camerafps.o \
		cameraorbit.o \
		camera.o
DIST          = ../../Qt/5.11.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/lex.prf \
		Shadify2.pro shader.h \
		vertex.h \
		mesh.h \
		object.h \
		glfwwindow.h \
		scene.h \
		abstract_event_handler.h \
		texture.h \
		model.h \
		stb_image/stb_image.h \
		light.h \
		renderengine.h \
		camerafps.h \
		cameraorbit.h \
		camera.h \
		env_scene.h main.cpp \
		shader.cpp \
		mesh.cpp \
		object.cpp \
		glfwwindow.cpp \
		scene.cpp \
		abstract_event_handler.cpp \
		model.cpp \
		light.cpp \
		renderengine.cpp \
		camerafps.cpp \
		cameraorbit.cpp \
		camera.cpp
QMAKE_TARGET  = Shadify2
DESTDIR       = 
TARGET        = Shadify2


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Shadify2.pro ../../Qt/5.11.1/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt/5.11.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.11.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.11.1/gcc_64/mkspecs/features/lex.prf \
		Shadify2.pro
	$(QMAKE) -o Makefile Shadify2.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../Qt/5.11.1/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt/5.11.1/gcc_64/mkspecs/common/unix.conf:
../../Qt/5.11.1/gcc_64/mkspecs/common/linux.conf:
../../Qt/5.11.1/gcc_64/mkspecs/common/sanitize.conf:
../../Qt/5.11.1/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt/5.11.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt/5.11.1/gcc_64/mkspecs/common/g++-base.conf:
../../Qt/5.11.1/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt/5.11.1/gcc_64/mkspecs/qconfig.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.11.1/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/qt_config.prf:
../../Qt/5.11.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt/5.11.1/gcc_64/mkspecs/features/spec_post.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/toolchain.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/default_pre.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/default_post.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/qml_debug.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/warn_on.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/qmake_use.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/file_copies.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/exceptions.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/yacc.prf:
../../Qt/5.11.1/gcc_64/mkspecs/features/lex.prf:
Shadify2.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Shadify2.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp GL/glew.h \
		GLFW/glfw3.h \
		glfwwindow.h \
		scene.h \
		model.h \
		shader.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		mesh.h \
		object.h \
		vertex.h \
		texture.h \
		cameraorbit.h \
		camera.h \
		light.h \
		abstract_event_handler.h \
		renderengine.h \
		stb_image/stb_image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

shader.o: shader.cpp GL/glew.h \
		shader.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shader.o shader.cpp

mesh.o: mesh.cpp mesh.h \
		GL/glew.h \
		object.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		shader.h \
		vertex.h \
		texture.h \
		glm/gtx/string_cast.hpp \
		glm/gtc/type_precision.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/vec1.hpp \
		glm/gtc/vec1.inl \
		glm/gtc/type_precision.inl \
		glm/gtx/dual_quaternion.hpp \
		glm/gtx/dual_quaternion.inl \
		glm/gtx/string_cast.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesh.o mesh.cpp

object.o: object.cpp object.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		shader.h \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/matrix_transform.inl \
		glm/gtx/string_cast.hpp \
		glm/gtc/type_precision.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/quaternion.inl \
		glm/gtc/vec1.hpp \
		glm/gtc/vec1.inl \
		glm/gtc/type_precision.inl \
		glm/gtx/dual_quaternion.hpp \
		glm/gtx/dual_quaternion.inl \
		glm/gtx/string_cast.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object.o object.cpp

glfwwindow.o: glfwwindow.cpp glfwwindow.h \
		scene.h \
		model.h \
		shader.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		mesh.h \
		GL/glew.h \
		object.h \
		vertex.h \
		texture.h \
		cameraorbit.h \
		camera.h \
		light.h \
		abstract_event_handler.h \
		GLFW/glfw3.h \
		renderengine.h \
		stb_image/stb_image.h \
		glm/gtx/string_cast.hpp \
		glm/gtc/type_precision.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/vec1.hpp \
		glm/gtc/vec1.inl \
		glm/gtc/type_precision.inl \
		glm/gtx/dual_quaternion.hpp \
		glm/gtx/dual_quaternion.inl \
		glm/gtx/string_cast.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glfwwindow.o glfwwindow.cpp

scene.o: scene.cpp scene.h \
		model.h \
		shader.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		mesh.h \
		GL/glew.h \
		object.h \
		vertex.h \
		texture.h \
		cameraorbit.h \
		camera.h \
		light.h \
		glm/gtx/string_cast.hpp \
		glm/gtc/type_precision.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/vec1.hpp \
		glm/gtc/vec1.inl \
		glm/gtc/type_precision.inl \
		glm/gtx/dual_quaternion.hpp \
		glm/gtx/dual_quaternion.inl \
		glm/gtx/string_cast.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scene.o scene.cpp

abstract_event_handler.o: abstract_event_handler.cpp abstract_event_handler.h \
		GLFW/glfw3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abstract_event_handler.o abstract_event_handler.cpp

model.o: model.cpp model.h \
		shader.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		mesh.h \
		GL/glew.h \
		object.h \
		vertex.h \
		texture.h \
		glm/gtx/string_cast.hpp \
		glm/gtc/type_precision.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/vec1.hpp \
		glm/gtc/vec1.inl \
		glm/gtc/type_precision.inl \
		glm/gtx/dual_quaternion.hpp \
		glm/gtx/dual_quaternion.inl \
		glm/gtx/string_cast.inl \
		stb_image/stb_image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o model.cpp

light.o: light.cpp light.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		object.h \
		shader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o light.o light.cpp

renderengine.o: renderengine.cpp renderengine.h \
		shader.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		scene.h \
		model.h \
		mesh.h \
		GL/glew.h \
		object.h \
		vertex.h \
		texture.h \
		cameraorbit.h \
		camera.h \
		light.h \
		stb_image/stb_image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderengine.o renderengine.cpp

camerafps.o: camerafps.cpp camerafps.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		camera.h \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/matrix_transform.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camerafps.o camerafps.cpp

cameraorbit.o: cameraorbit.cpp cameraorbit.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		camera.h \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/matrix_transform.inl \
		glm/gtx/string_cast.hpp \
		glm/gtc/type_precision.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/quaternion.inl \
		glm/gtc/vec1.hpp \
		glm/gtc/vec1.inl \
		glm/gtc/type_precision.inl \
		glm/gtx/dual_quaternion.hpp \
		glm/gtx/dual_quaternion.inl \
		glm/gtx/string_cast.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cameraorbit.o cameraorbit.cpp

camera.o: camera.cpp camera.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/matrix_transform.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

